#!/bin/bash
echo "Installing packages..."
pip install notebook jupyterlab jupyterhub-nativeauthenticator nbgitpuller

echo "Creating configuration..."
mkdir /etc/jupyterhub

jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py

echo "Patching configuration file..."

cat <<EOF >> /etc/jupyterhub/jupyterhub_config.py
import os, nativeauthenticator, pwd, subprocess
c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
c.JupyterHub.template_paths = [f"{os.path.dirname(nativeauthenticator.__file__)}/templates/"]
c.Authenticator.admin_users = {'admin'}
def pre_spawn_hook(spawner):
    user_name = spawner.user.name
    try:
        pwd.getpwnam(user_name)
    except KeyError:
        subprocess.check_call(['useradd', '-ms', '/bin/bash', user_name])

c.Spawner.pre_spawn_hook = pre_spawn_hook
# default instance is jupyterlb 
c.Spawner.default_url = '/tree'
EOF

echo "Copying template file..."
cp /usr/local/lib/python3.8/dist-packages/nbgitpuller/templates/status.html /usr/local/lib/python3.8/dist-packages/notebook/templates/

echo "Starting Jupyterhub..."
jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

